package config

var TeamUrls = [30]string{
	"https://www.espn.com/nba/team/stats/_/name/bos/boston-celtics",
	"https://www.espn.com/nba/team/stats/_/name/gs/golden-state-warriors",
	"https://www.espn.com/nba/team/stats/_/name/bkn/brooklyn-nets",
	"https://www.espn.com/nba/team/stats/_/name/lac/la-clippers",
	"https://www.espn.com/nba/team/stats/_/name/lal/los-angeles-lakers",
	"https://www.espn.com/nba/team/stats/_/name/ny/new-york-knicks",
	"https://www.espn.com/nba/team/stats/_/name/phi/philadelphia-76ers",
	"https://www.espn.com/nba/team/stats/_/name/phx/phoenix-suns",
	"https://www.espn.com/nba/team/stats/_/name/sac/sacramento-kings",
	"https://www.espn.com/nba/team/stats/_/name/tor/toronto-raptors",
	"https://www.espn.com/nba/team/stats/_/name/chi/chicago-bulls",
	"https://www.espn.com/nba/team/stats/_/name/atl/atlanta-hawks",
	"https://www.espn.com/nba/team/stats/_/name/cle/cleveland-cavaliers",
	"https://www.espn.com/nba/team/stats/_/name/cha/charlotter-hornets",
	"https://www.espn.com/nba/team/stats/_/name/det/detroit-pistons",
	"https://www.espn.com/nba/team/stats/_/name/mia/miami-heat",
	"https://www.espn.com/nba/team/stats/_/name/ind/indiana-pacers",
	"https://www.espn.com/nba/team/stats/_/name/orl/orlando-magic",
	"https://www.espn.com/nba/team/stats/_/name/wsh/washington-wizards",
	"https://www.espn.com/nba/team/stats/_/name/mil/milwaukee-bucks",
	"https://www.espn.com/nba/team/stats/_/name/den/denver-nuggets",
	"https://www.espn.com/nba/team/stats/_/name/dal/dallas-mavericks",
	"https://www.espn.com/nba/team/stats/_/name/sa/san-antonio-spurs",
	"https://www.espn.com/nba/team/stats/_/name/hou/houston-rockets",
	"https://www.espn.com/nba/team/stats/_/name/min/minnesota-timberwolves",
	"https://www.espn.com/nba/team/stats/_/name/okc/oklahoma-city-thunder",
	"https://www.espn.com/nba/team/stats/_/name/mem/memphis-grizzlies",
	"https://www.espn.com/nba/team/stats/_/name/no/new-orleans-pelicans",
	"https://www.espn.com/nba/team/stats/_/name/por/portland-trail-blazars",
	"https://www.espn.com/nba/team/stats/_/name/utah/utah-jazz",
}
